
obstacle_range: 2.0
raytrace_range: 4.0

transform_tolerance: 0.15 # 0.0

robot_radius: 0.3
inflation_radius: 2.0
inflation_unknown: false
cost_scaling_factor: 0.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true}
