global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 3.0
  publish_frequency: 3.0
  resolution: 0.05
  static_map: true #If using existing map must mark this 'true'
  rolling_window: false
  width: 4000.0
  height: 4000.0
  plugins:
   - {name: static_map,       type: "costmap_2d::StaticLayer"}
   - {name: obstacles,        type: "costmap_2d::VoxelLayer"}